= Compose BigLazyTable (Compose BLT)
:description: Compose BigLazyTable (Compose BLT) is a library that efficiently supports the handling of large amounts of data end-to-end in Compose for Desktop
:keywords: kotlin, lazy-loading, compose, compose-for-desktop
:author: Marco Sprenger; Livio Näf
:revnumber: v1.0.2
:revdate: 2022-04-11
[.clearfix]
--
https://jitpack.io/#FHNW-IP5-IP6/ComposeBigLazyTable[image:https://jitpack.io/v/FHNW-IP5-IP6/ComposeBigLazyTable.svg[]]
https://github.com/FHNW-IP5-IP6/ComposeBigLazyTable/actions/workflows/sonarqube.yml[image:https://github.com/FHNW-IP5-IP6/ComposeBigLazyTable/actions/workflows/sonarqube.yml/badge.svg[.github/workflows/sonarqube.yml]]

Compose BigLazyTable (Compose BLT) is a library that efficiently supports the handling of large amounts of data end-to-end in Compose for Desktop.

== Why does this Library exist?
Many desktop business applications today consist of a table showing all the data records and an appropriate form for editing the data. These applications need to provide appropriate functionality for the end user to work efficiently and comfortably.

For developers, there are appropriate building blocks in older programming languages, such as Java with JavaFX, to build such applications. Most of these applications are specially adapted to a company and come in a design that is no longer so up-to-date. In addition, with a JavaFX solution, the lazy loading, as well as a connection to a form, must still be programmed by the user. With Compose BigLazyTable, a library was developed using Kotlin and Compose for Desktop, with that developers can easily create a basic application, consisting of a table and a form for processing the data. Compose for Desktop uses Material Design for the UI building blocks by default, which offers a much more modern look. The table is provided with filters, sorting options and a lazy loading mechanism. Combined with a form from the ComposeForms library, Compose BigLazyTable offers the necessary functionalities familiar to users of JavaFX.

== Import Compose BigLazyTable
Compose BigLazyTable can be obtained from JitPack:

.Gradle-Groovy-DSL:
[source,groovy]
----
implementation 'com.github.FHNW-IP5-IP6:ComposeBigLazyTable:v1.0.2'
----

.Gradle-Kotlin-DSL:
[source,groovy]
----
implementation("com.github.FHNW-IP5-IP6:ComposeBigLazyTable:v1.0.2")
----

== Developer Guide

* xxx

=== xxx
xxx

== Demo Applications
* *ComposeForms* _(demo > src > main > kotlin > demo > composeForms)_ +
Demo project for Compose Forms

* *BigLazyTable* _(demo > src > main > kotlin > demo > bigLazyTable)_ +
Demo projects for Compose BigLazyTable combined with Compose Forms


