package demo.biglazytable.model

data class BigDatasetModel(
    val name: String,
    val collaborative: String,
    val modified_at: Int,
    val num_tracks: Int,
    val num_albums: Int,
    val num_followers: Int,
    val num_edits: Int,
    val duration_ms: Int,
    val num_artists: Int,
    val track0_artist_name: String,
    val track0_track_name: String,
    val track0_duration_ms: Int,
    val track0_album_name: String,
    val track1_artist_name: String,
    val track1_track_name: String,
    val track1_duration_ms: Int,
    val track1_album_name: String,
    val track2_artist_name: String,
    val track2_track_name: String,
    val track2_duration_ms: Int,
    val track2_album_name: String,
    val track3_artist_name: String,
    val track3_track_name: String,
    val track3_duration_ms: String,
    val track3_album_name: String,
    val track4_artist_name: String,
    val track4_track_name: String,
    val track4_duration_ms: String,
    val track4_album_name: String,
)
