name: Sonarqube
on:
  push:
    branches:
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./gradlew test -i
      - run: ./gradlew build demo:sonarqube -Dsonar.projectKey=demo -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.sources=src/main -Dsonar.coverage.exclusions="**.*"
      - run: ./gradlew build desktop:sonarqube -Dsonar.projectKey=desktop -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.sources=src/main -Dsonar.coverage.exclusions="**.*"
      - run: ./gradlew build common:sonarqube -Dsonar.projectKey=common -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.sources=src/main -Dsonar.coverage.exclusions="**.*"
